apiVersion: v1
kind: Service
metadata:
  name: demo-rancher-1
  namespace: team1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: demo-rancher-1