# internal-back-java-1
apiVersion: v1
kind: Service
metadata:
  name: internal-back-java-1
  namespace: team1
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: internal-back-java-1