apiVersion: apps/v1
kind: Deployment
metadata:
  name: connected-back-java-1
  namespace: team1
spec:
  selector:
    matchLabels:
      app: connected-back-java-1
  replicas: 1
  template:
    metadata:
      labels:
        app: connected-back-java-1
    spec:
      containers:
        - name: connected-back-java-1
          image: leddzip/demo-rancher-back-connected-service-java-1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: "{\"internal-service\":{ \"base-url\": \"http://internal-back-java-1\"}}"
