GET http://localhost:3001/api/v1/employees
Accept: application/json

###

GET http://localhost:3001/api/v1/employees/1
Accept: application/json

###

POST http://localhost:3001/api/v1/employees
Content-Type: application/json

{
  "first_name": "me name",
  "last_name": "me last name",
  "email": "me@mail.com"
}

###

# This is a faulty content to show that a put method will insert
# the json pass in parameter, regardless of the coherence with the
# other entries
POST http://localhost:3001/api/v1/employees
Content-Type: application/json

{
  "me_name": "name"
}

###

# this will delete the content and replace it with the provided content
PUT http://localhost:3001/api/v1/employees/1
Content-Type: application/json

{
  "first_name": "me"
}

###
PATCH http://localhost:3001/api/v1/employees/1
Content-Type: application/json

{
  "firstname": "me",
  "first_name": "me"
}

###
DELETE http://localhost:3001/api/v1/employees/1
Accept: application/json

###
GET http://localhost:3001/api/v1/departments
Accept: application/json

###
GET http://localhost:3001/api/v1/departments/it
Accept: application/json

###
# won't work since it can't get back the id
POST http://localhost:3001/api/v1/departments
Content-Type: application/json

{
  "code": 4,
  "name": "un-accessible"
}

###
# 1 chance out of 5 to return an error
POST http://localhost:3001/api/v1/departments/it/risk
Content-Type: application/json

{}

###
# will always succeed
POST http://localhost:3001/api/v1/departments/legal/complaints
Content-Type: application/json

{}
