apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-back-java-1
  namespace: team1
spec:
  selector:
    matchLabels:
      app: basic-back-java-1
  replicas: 1
  template:
    metadata:
      labels:
        app: basic-back-java-1
    spec:
      containers:
        - name: basic-back-java-1
          image: leddzip/demo-rancher-back-basic-java-1:1.1.1
          imagePullPolicy: Always
          ports:
              - containerPort: 8080
      restartPolicy: Always