apiVersion: v1
kind: Service
metadata:
  name: basic-back-python-1
  namespace: team1
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31002
  selector:
    app: basic-back-python-1