k8s-01:
	kubectl --kubeconfig kubeconfig apply -f 01-namespace-infra.yml

k8s-02:
	kubectl --kubeconfig kubeconfig apply -f 02-namespace-team1.yml

k8s-03:
	kubectl --kubeconfig kubeconfig apply -f 03-deployment-front-one.yml

k8s-04:
	kubectl --kubeconfig kubeconfig apply -f 04-service-front-one.yml

k8s-05:
	kubectl --kubeconfig kubeconfig apply -f 05-deployment-back-basic-java.yml

k8s-06:
	kubectl --kubeconfig kubeconfig apply -f 06-service-back-basic-java.yml

k8s-07:
	kubectl --kubeconfig kubeconfig apply -f 07-deployment-back-basic-python.yml

k8s-08:
	kubectl --kubeconfig kubeconfig apply -f 08-service-back-basic-python.yml

k8s-09:
	kubectl --kubeconfig kubeconfig apply -f 09-deployment-back-internal-service-java.yml

k8s-10:
	kubectl --kubeconfig kubeconfig apply -f 10-service-back-internal-java.yml

k8s-11:
	kubectl --kubeconfig kubeconfig apply -f 11-deployment-back-connected-service-java.yml

k8s-12:
	kubectl --kubeconfig kubeconfig apply -f 12-service-back-connected-service-java.yml
